<?php

namespace AppBundle\Repository;

/**
 * PassagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportingRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllFilter( $chauffeurSearch)
    {
        //Requete dql
    }
}
